services:
  postgres:
    container_name: festadosbairrosapi-pg
    image: bitnami/postgresql
    ports:
      - 5433:5433
    environment:
      - POSTGRESQL_USERNAME=festadosbairros
      - POSTGRESQL_PASSWORD=festadosbairros
      - POSTGRESQL_DATABASE=festadosbairrosapi
    volumes:
      - ./data/pg:/data/postgres
