// src/reset-prices/default-prices.ts
export type ProductDefault = { name: string; price: number };

export const DEFAULT_PRICES: ProductDefault[] = [
  { name: "Batata grande com cheddar e calabresa", price: 20.0 },
  { name: "Batata pequena", price: 10.0 },
  { name: "Carne", price: 10.0 },
  { name: "Misto", price: 9.0 },
  { name: "Frango", price: 8.0 },
  { name: "Salsichão", price: 7.0 },
  { name: "Queijo coalho", price: 10.0 },
  { name: "Hot filadélfia", price: 20.0 },
  { name: "Yakisoba carne", price: 18.0 },
  { name: "Yakisoba frango", price: 15.0 },
  { name: "Pancho (pão com linguiça e queijo)", price: 12.0 },
  { name: "Cheddar Melt artesanal", price: 25.0 },
  { name: "Hamburguer tradicional (x-bacon)", price: 12.0 },
  { name: "Hamburguer tradicional duplo", price: 18.0 },
  { name: "Torta de limão", price: 12.0 },
  { name: "Bolo de cenoura", price: 8.0 },
  { name: "Bolo de aipim", price: 7.0 },
  { name: "Banofe", price: 12.0 },
  { name: "Torta de chocolate", price: 12.0 },
  { name: "Cuzcuz", price: 7.0 },
  { name: "Bolo de milho", price: 7.0 },
  { name: "Pudim", price: 8.0 },
  { name: "Camarão", price: 13.0 },
  { name: "Queijo", price: 10.0 },
  { name: "Pizza", price: 10.0 },
  { name: "Caldo de Aipim com carne seca", price: 16.0 },
  { name: "Caldo de mocotó", price: 16.0 },
  { name: "Caldo Verde", price: 14.0 },
  { name: "Canjica", price: 12.0 },
  { name: "Milho verde", price: 7.0 },
  { name: "Guaracamp 250ml", price: 3.0 },
  { name: "Refrigerante 350 ml", price: 7.0 },
  { name: "Coquetel 400ml", price: 8.0 },
  { name: "Água mineral 500 ml", price: 2.0 },
  { name: "Café", price: 5.0 },
  { name: "Chocolate quente", price: 6.0 },
  { name: "Açaí 300ml", price: 12.0 },
  { name: "Açaí 400ml", price: 14.0 },
];
